version: 2
jobs:
  build:
    working_directory: ~/website-changed
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-

      - run: npm install

      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: npm run-script test
